[project]
name = "tabpfn"
version = "0.1.0"
description = "Testing out TabPFN and benchmarking against XGBoost"
readme = "README.md"
authors = [
    { name = "Daniel Jensen", email = "jensendaniel0144@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
  "tabpfn",
  "xgboost",
  "pandas",
  "numpy",
  "matplotlib",
  "scikit-learn",
  "requests",
  "dotenv",
]

[project.scripts]
tabpfn = "tabpfn:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
